In [1]:
import numpy as np

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a, a.mean(), a.sum(), a.min(), a.max())

[1 2 3] 2.0 6 1 3


In [3]:
x = np.arange(5)
print(x[1:4])
print(x[::-1])



[1 2 3]
[4 3 2 1 0]


In [4]:
zeros = np.zeros(6)
ones = np.ones((3, 3))
ar = np.arange(0, 10, 2)

zeros, ones, ar

(array([0., 0., 0., 0., 0., 0.]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 2, 4, 6, 8]))

In [5]:
print("a:", a)
print("shape:", a.shape)
print("ndim:", a.ndim)
print("dtype", a.dtype)

a: [1 2 3]
shape: (3,)
ndim: 1
dtype int64


In [6]:
grades = np.array([6, 7, 8, 9, 10])

print("Оценки:", grades)
print("Средний балл:", grades.mean())

grades_min = grades.min()
grades_max = grades.max()
norm_grades = (grades - grades_min) / (grades_max - grades_min)

print("Нормализованные оценки:", norm_grades)


Оценки: [ 6  7  8  9 10]
Средний балл: 8.0
Нормализованные оценки: [0.   0.25 0.5  0.75 1.  ]
